use common::types::{Side, SliceState};

/// Child order slice generated by the VWAP algorithm.
///
/// Ported from Java `Slice.java`. Uses init/reset pool pattern.
pub struct Slice {
    pub slice_id: u64,
    pub parent_algo_order_id: u64,
    pub symbol_index: u32,
    pub side: Side,
    pub quantity: u64,
    pub price: u64,
    pub slice_number: u32,

    // Execution tracking
    pub executed_quantity: u64,
    pub executed_price: u64,
    pub leaves_quantity: u64,

    // State
    pub state: SliceState,

    // Timestamps
    pub create_timestamp: u64,
    pub sent_timestamp: u64,
    pub last_update_timestamp: u64,
}

impl Default for Slice {
    fn default() -> Self {
        Self {
            slice_id: 0,
            parent_algo_order_id: 0,
            symbol_index: 0,
            side: Side::Buy,
            quantity: 0,
            price: 0,
            slice_number: 0,
            executed_quantity: 0,
            executed_price: 0,
            leaves_quantity: 0,
            state: SliceState::Pending,
            create_timestamp: 0,
            sent_timestamp: 0,
            last_update_timestamp: 0,
        }
    }
}

impl Slice {
    /// Initialize a slice for a new child order.
    #[allow(clippy::too_many_arguments)]
    pub fn init(
        &mut self,
        slice_id: u64,
        parent_algo_order_id: u64,
        symbol_index: u32,
        side: Side,
        quantity: u64,
        price: u64,
        slice_number: u32,
        timestamp: u64,
    ) {
        self.slice_id = slice_id;
        self.parent_algo_order_id = parent_algo_order_id;
        self.symbol_index = symbol_index;
        self.side = side;
        self.quantity = quantity;
        self.price = price;
        self.slice_number = slice_number;
        self.executed_quantity = 0;
        self.executed_price = 0;
        self.leaves_quantity = quantity;
        self.state = SliceState::Pending;
        self.create_timestamp = timestamp;
        self.sent_timestamp = 0;
        self.last_update_timestamp = timestamp;
    }

    /// Reset for pool reuse.
    pub fn reset(&mut self) {
        *self = Self::default();
    }

    /// Mark as sent to SOR.
    pub fn mark_sent(&mut self, timestamp: u64) {
        self.state = SliceState::Sent;
        self.sent_timestamp = timestamp;
        self.last_update_timestamp = timestamp;
    }

    /// Mark as acknowledged by venue.
    pub fn mark_acked(&mut self, timestamp: u64) {
        self.state = SliceState::Acked;
        self.last_update_timestamp = timestamp;
    }

    /// Record an execution fill. Updates VWAP price.
    pub fn on_execution(&mut self, exec_qty: u64, exec_price: u64, timestamp: u64) {
        let total_value = self.executed_price as u128 * self.executed_quantity as u128
            + exec_price as u128 * exec_qty as u128;
        self.executed_quantity += exec_qty;
        self.leaves_quantity = self.leaves_quantity.saturating_sub(exec_qty);
        self.executed_price = if self.executed_quantity > 0 {
            (total_value / self.executed_quantity as u128) as u64
        } else {
            0
        };
        self.last_update_timestamp = timestamp;

        if self.leaves_quantity == 0 {
            self.state = SliceState::Filled;
        } else {
            self.state = SliceState::PartialFill;
        }
    }

    pub fn mark_cancelled(&mut self, timestamp: u64) {
        self.state = SliceState::Cancelled;
        self.last_update_timestamp = timestamp;
    }

    pub fn mark_rejected(&mut self, timestamp: u64) {
        self.state = SliceState::Rejected;
        self.last_update_timestamp = timestamp;
    }

    pub fn is_filled(&self) -> bool {
        self.state == SliceState::Filled
    }

    pub fn is_terminal(&self) -> bool {
        self.state.is_terminal()
    }
}

impl common::pool::Poolable for Slice {
    fn reset(&mut self) {
        Slice::reset(self);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_slice() -> Slice {
        let mut s = Slice::default();
        s.init(1, 100, 0, Side::Buy, 500, 15_000_000, 1, 1000);
        s
    }

    #[test]
    fn test_slice_init() {
        let s = make_slice();
        assert_eq!(s.slice_id, 1);
        assert_eq!(s.quantity, 500);
        assert_eq!(s.leaves_quantity, 500);
        assert_eq!(s.state, SliceState::Pending);
    }

    #[test]
    fn test_slice_lifecycle() {
        let mut s = make_slice();

        s.mark_sent(1100);
        assert_eq!(s.state, SliceState::Sent);

        s.mark_acked(1200);
        assert_eq!(s.state, SliceState::Acked);

        // Partial fill
        s.on_execution(200, 15_000_000, 1300);
        assert_eq!(s.state, SliceState::PartialFill);
        assert_eq!(s.executed_quantity, 200);
        assert_eq!(s.leaves_quantity, 300);

        // Complete fill
        s.on_execution(300, 15_100_000, 1400);
        assert_eq!(s.state, SliceState::Filled);
        assert_eq!(s.leaves_quantity, 0);
        assert!(s.is_filled());
        assert!(s.is_terminal());
    }

    #[test]
    fn test_slice_vwap_price() {
        let mut s = make_slice();
        s.mark_sent(1100);

        // Fill 200 @ 15_000_000
        s.on_execution(200, 15_000_000, 1200);
        assert_eq!(s.executed_price, 15_000_000);

        // Fill 300 @ 15_200_000
        // VWAP = (200*15M + 300*15.2M) / 500 = (3B + 4.56B) / 500 = 15_120_000
        s.on_execution(300, 15_200_000, 1300);
        assert_eq!(s.executed_price, 15_120_000);
    }

    #[test]
    fn test_slice_cancel() {
        let mut s = make_slice();
        s.mark_sent(1100);
        s.mark_cancelled(1200);
        assert!(s.is_terminal());
    }

    #[test]
    fn test_slice_reset() {
        let mut s = make_slice();
        s.mark_sent(1100);
        s.on_execution(200, 15_000_000, 1200);
        s.reset();
        assert_eq!(s.slice_id, 0);
        assert_eq!(s.state, SliceState::Pending);
        assert_eq!(s.executed_quantity, 0);
    }
}
