package com.microoptimus.algo.slice;

import com.microoptimus.common.types.Side;

/**
 * Slice - Pooled child order object generated by algorithm
 */
public class Slice {

    // Identifiers
    private long sliceId;
    private long parentAlgoOrderId;
    private int symbolIndex;

    // Order attributes
    private Side side;
    private long quantity;
    private long price;
    private int sliceNumber;

    // Execution
    private long executedQuantity;
    private long executedPrice;
    private long leavesQuantity;

    // State
    private SliceState state;

    // Timestamps
    private long createTimestamp;
    private long sentTimestamp;
    private long lastUpdateTimestamp;

    // Pool management
    private boolean inPool;

    public enum SliceState {
        PENDING,       // Created, not yet sent
        SENT,          // Sent to SOR
        ACKED,         // Acknowledged by venue
        PARTIAL_FILL,  // Partially filled
        FILLED,        // Fully filled
        CANCELLED,     // Cancelled
        REJECTED       // Rejected
    }

    public Slice() {
        this.state = SliceState.PENDING;
        this.inPool = true;
    }

    /**
     * Initialize slice
     */
    public void init(long sliceId, long parentAlgoOrderId, int symbolIndex,
                     Side side, long quantity, long price, int sliceNumber, long timestamp) {
        this.sliceId = sliceId;
        this.parentAlgoOrderId = parentAlgoOrderId;
        this.symbolIndex = symbolIndex;
        this.side = side;
        this.quantity = quantity;
        this.price = price;
        this.sliceNumber = sliceNumber;
        this.executedQuantity = 0;
        this.executedPrice = 0;
        this.leavesQuantity = quantity;
        this.state = SliceState.PENDING;
        this.createTimestamp = timestamp;
        this.sentTimestamp = 0;
        this.lastUpdateTimestamp = timestamp;
        this.inPool = false;
    }

    /**
     * Reset for return to pool
     */
    public void reset() {
        this.sliceId = 0;
        this.parentAlgoOrderId = 0;
        this.symbolIndex = 0;
        this.side = null;
        this.quantity = 0;
        this.price = 0;
        this.sliceNumber = 0;
        this.executedQuantity = 0;
        this.executedPrice = 0;
        this.leavesQuantity = 0;
        this.state = SliceState.PENDING;
        this.createTimestamp = 0;
        this.sentTimestamp = 0;
        this.lastUpdateTimestamp = 0;
        this.inPool = true;
    }

    /**
     * Mark as sent to SOR
     */
    public void markSent(long timestamp) {
        this.state = SliceState.SENT;
        this.sentTimestamp = timestamp;
        this.lastUpdateTimestamp = timestamp;
    }

    /**
     * Mark as acknowledged
     */
    public void markAcked(long timestamp) {
        this.state = SliceState.ACKED;
        this.lastUpdateTimestamp = timestamp;
    }

    /**
     * Record execution
     */
    public void onExecution(long execQty, long execPrice, long timestamp) {
        // Update VWAP
        long totalValue = (executedPrice * executedQuantity) + (execPrice * execQty);
        executedQuantity += execQty;
        leavesQuantity -= execQty;
        executedPrice = executedQuantity > 0 ? totalValue / executedQuantity : 0;
        lastUpdateTimestamp = timestamp;

        if (leavesQuantity == 0) {
            state = SliceState.FILLED;
        } else {
            state = SliceState.PARTIAL_FILL;
        }
    }

    /**
     * Mark as cancelled
     */
    public void markCancelled(long timestamp) {
        this.state = SliceState.CANCELLED;
        this.lastUpdateTimestamp = timestamp;
    }

    /**
     * Mark as rejected
     */
    public void markRejected(long timestamp) {
        this.state = SliceState.REJECTED;
        this.lastUpdateTimestamp = timestamp;
    }

    // Getters
    public long getSliceId() { return sliceId; }
    public long getParentAlgoOrderId() { return parentAlgoOrderId; }
    public int getSymbolIndex() { return symbolIndex; }
    public Side getSide() { return side; }
    public long getQuantity() { return quantity; }
    public long getPrice() { return price; }
    public int getSliceNumber() { return sliceNumber; }
    public long getExecutedQuantity() { return executedQuantity; }
    public long getExecutedPrice() { return executedPrice; }
    public long getLeavesQuantity() { return leavesQuantity; }
    public SliceState getState() { return state; }
    public long getCreateTimestamp() { return createTimestamp; }
    public long getSentTimestamp() { return sentTimestamp; }
    public long getLastUpdateTimestamp() { return lastUpdateTimestamp; }
    public boolean isInPool() { return inPool; }

    // State queries
    public boolean isFilled() { return state == SliceState.FILLED; }
    public boolean isTerminal() {
        return state == SliceState.FILLED ||
               state == SliceState.CANCELLED ||
               state == SliceState.REJECTED;
    }

    @Override
    public String toString() {
        return String.format("Slice{id=%d, parent=%d, #%d, %s %d@%d, exec=%d, state=%s}",
                sliceId, parentAlgoOrderId, sliceNumber, side, quantity, price,
                executedQuantity, state);
    }
}
