use common::messages::{VwapParamsMsg, MAX_BUCKETS};

/// VWAP parameters generated by the signal module.
#[derive(Clone)]
pub struct VwapParams {
    pub num_buckets: usize,
    pub participation_rate: f64,
    pub min_slice_size: u64,
    pub max_slice_size: u64,
    pub slice_interval_ns: u64,
    pub volume_profile: [f64; MAX_BUCKETS],
}

impl Default for VwapParams {
    fn default() -> Self {
        Self {
            num_buckets: 10,
            participation_rate: 0.10,
            min_slice_size: 100,
            max_slice_size: 10_000,
            slice_interval_ns: 1_000_000_000, // 1 second
            volume_profile: [0.0; MAX_BUCKETS],
        }
    }
}

/// Generates VWAP parameters including the U-shaped volume profile.
///
/// Ported from Java `VWAPAlgorithm.createDefaultVolumeProfile()`.
pub struct VwapParameterGenerator {
    params: VwapParams,
}

impl VwapParameterGenerator {
    pub fn new() -> Self {
        let mut gen = Self {
            params: VwapParams::default(),
        };
        gen.generate_volume_profile();
        gen
    }

    /// Create with custom configuration.
    pub fn with_config(
        num_buckets: usize,
        participation_rate: f64,
        min_slice_size: u64,
        max_slice_size: u64,
        slice_interval_ns: u64,
    ) -> Self {
        assert!((2..=MAX_BUCKETS).contains(&num_buckets));
        let mut gen = Self {
            params: VwapParams {
                num_buckets,
                participation_rate,
                min_slice_size,
                max_slice_size,
                slice_interval_ns,
                volume_profile: [0.0; MAX_BUCKETS],
            },
        };
        gen.generate_volume_profile();
        gen
    }

    /// Generate the U-shaped volume profile.
    ///
    /// Formula: `profile[i] = 1.0 + 0.5 * (2 * position - 1)^2`
    /// Higher volume at market open (i=0) and close (i=N-1), lower in the middle.
    /// Normalized so the profile sums to 1.0.
    fn generate_volume_profile(&mut self) {
        let n = self.params.num_buckets;
        let mut total = 0.0;

        for i in 0..n {
            let position = i as f64 / (n - 1) as f64; // 0.0 to 1.0
            let val = 1.0 + 0.5 * (2.0 * position - 1.0).powi(2);
            self.params.volume_profile[i] = val;
            total += val;
        }

        // Normalize to sum to 1.0
        for i in 0..n {
            self.params.volume_profile[i] /= total;
        }
    }

    /// Get the current VWAP parameters.
    pub fn params(&self) -> &VwapParams {
        &self.params
    }

    /// Encode parameters into a wire-format message.
    pub fn to_msg(&self, symbol_index: u32, timestamp: u64) -> VwapParamsMsg {
        VwapParamsMsg {
            symbol_index,
            num_buckets: self.params.num_buckets as u32,
            participation_rate: self.params.participation_rate,
            min_slice_size: self.params.min_slice_size,
            max_slice_size: self.params.max_slice_size,
            slice_interval_ns: self.params.slice_interval_ns,
            volume_profile: self.params.volume_profile,
            timestamp,
        }
    }
}

impl Default for VwapParameterGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_volume_profile_sums_to_one() {
        let gen = VwapParameterGenerator::new();
        let params = gen.params();
        let sum: f64 = params.volume_profile[..params.num_buckets].iter().sum();
        assert!((sum - 1.0).abs() < 1e-10, "profile sum = {}", sum);
    }

    #[test]
    fn test_u_shape_edges_greater_than_center() {
        let gen = VwapParameterGenerator::new();
        let p = gen.params();
        let n = p.num_buckets;
        let center = n / 2;

        // Edges should be higher than center
        assert!(
            p.volume_profile[0] > p.volume_profile[center],
            "edge[0]={} should be > center[{}]={}",
            p.volume_profile[0],
            center,
            p.volume_profile[center]
        );
        assert!(
            p.volume_profile[n - 1] > p.volume_profile[center],
            "edge[{}]={} should be > center[{}]={}",
            n - 1,
            p.volume_profile[n - 1],
            center,
            p.volume_profile[center]
        );
    }

    #[test]
    fn test_symmetric_profile() {
        let gen = VwapParameterGenerator::new();
        let p = gen.params();
        let n = p.num_buckets;

        for i in 0..n / 2 {
            let diff = (p.volume_profile[i] - p.volume_profile[n - 1 - i]).abs();
            assert!(diff < 1e-10, "profile not symmetric at bucket {}", i);
        }
    }

    #[test]
    fn test_custom_config() {
        let gen = VwapParameterGenerator::with_config(20, 0.15, 50, 5000, 500_000_000);
        let p = gen.params();
        assert_eq!(p.num_buckets, 20);
        assert!((p.participation_rate - 0.15).abs() < f64::EPSILON);
        assert_eq!(p.min_slice_size, 50);
        assert_eq!(p.max_slice_size, 5000);

        let sum: f64 = p.volume_profile[..20].iter().sum();
        assert!((sum - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_to_msg() {
        let gen = VwapParameterGenerator::new();
        let msg = gen.to_msg(42, 1000);
        assert_eq!(msg.symbol_index, 42);
        assert_eq!(msg.num_buckets, 10);
        assert_eq!(msg.timestamp, 1000);
        assert!((msg.participation_rate - 0.10).abs() < f64::EPSILON);
    }
}
