[package]
name = "marketdata"
version.workspace = true
edition.workspace = true

[features]
aeron-integration = ["common/aeron"]
chronicle-integration = ["common/chronicle"]

[dependencies]
common = { path = "../common" }

[[bin]]
name = "marketdata_aeron_service"
required-features = ["aeron-integration"]

[[bin]]
name = "marketdata_chronicle_service"
required-features = ["chronicle-integration"]

